### PR TITLE
Complete clone functionality and design

### PR DESCRIPTION
**Pull request by ibraheemkabir**
# Youtube-Clone 

# What does this pull request do?
This pull request contains the implementation of the YouTube-clone task. 

# What tasks does this pull request accomplish
- Creation of navigation bar containing the logo, search button, and field as well as the upload and sign-in button.
- The main section area contains a video playback as well as the suggestions thumbnails.
- A footer similar to that of the youtube homepage

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Fantastic job guys! Your page is unique :smile: 
You've done an awesome job building this, however, before you may merge, there are a few things I will highlight that require your attention.

#### HTML Validations
Your page is beautifully structures, however, there are some semantic errors I noticed, things like elements sharing IDs and missing tags, etc. Please consider using this [validation tool](https://validator.w3.org
) to ensure your markup is as exquisite as your page looks :smile:. Also take a look at the requirement below this bit of text.
screenshot

#### Recommended Videos
Your recommended videos section looks great! Please give this one requirement a look and try to correct them so you can move on.
* You should have video thumbnails showing up in this section and not hard coded pictures
screenshot

#### Navbar
Just like the rest of your work, it looks great, however, it is necessary that you have at least 3 images embedded in the rightmost part of the navigation. Please see the requirement below.
screenshot

# Summary
Your work is great! You just need to dive back in and look into the semantic strength of your markup and  using the tool I provided above will make that very easy. You also need to look at your recommended videos section as well as the navigation bar. When these three things are done, you can submit for a re-review :+1:.

Feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilareolusakin) if you have any code related questions/issues or you just want to chat :smile: I am always happy to help.

**Review by fatymahmed — COMMENTED** [review]
### Hi @ibraheemkabir @Mindo-Joseph,
**Great job** on fixing the recommended videos section as requested by the previous TSE, 👏👏 however, there are still a few things to fix before you can merge.

- I noticed you used buttons at the top right side of the navbar, but please use images as it's mentioned in the requirements that
the navbar should have **at least three embedded images** on the rightmost part of the navbar that represent icons and/or an avatar, see [screenshot of the requirement](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/icons_requirement.png) from Pathwright) 

- I also noticed that you have some errors in your markup, so please check your HTML markup with this [validator](https://validator.w3.org) as mentioned in the requirements,[screenshot of requirement](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/validation_requirement.png) from Pathwright.

Please fix these errors
Screenshot from 2019-12-24 15-24-16

**[OPTIONAL]**
The following suggestions are optional and you don't need to change them but it's considered a good practice to do them.
 - You could use the `<nav>` tag for the major navigation links.
 - You could use the `<main>` tag for the dominant content of the <body> of a document

**Review by fatymahmed — CHANGES_REQUESTED** [review]
### Please make the suggested changes and request for another code review
## Status: Changes Required

_Feel free to reach out to me on Slack (fatima) if you have any questions or need any help._

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Great job  @ibraheemkabir and @Mindo-Joseph! :rocket: 

You did nice work handling some of the previously requested changes, however, you still have some buttons going on in the right section of your navigation bar as @fatymahmed rightly pointed out and as such I cannot approve the project. 

Please refer to her comment about your navigation bar, make required changes and request a re-review.

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Nice job trying to implement said changes @ibraheemkabir and @Mindo-Joseph!
Please look more closely at the kind and style of images on the original page's navbar and follow suit. From what I see, you have a button-like image in you navigation which messes up the look of your project. Please correct and request another review :handshake:.

**Comment by Mindo-Joseph** [comment]
Thanks!  Which button is that because I have used images throughout 😁

**Pull request closed without merging**
